feat: added home page banners to UI
Developer-DAO/academy-turbo pull request #13
Opened 2023-09-22 12:02 UTC by peteruche21

## Changes

- Learn Web 3 homepage section
- DD partner homepage section

## API Updates
null

### screenshots

![issue9](https://github.com/Developer-DAO/academy-turbo/assets/53627398/de4b37f2-03fe-484f-a10f-0f76213baa48)
![issue10](https://github.com/Developer-DAO/academy-turbo/assets/53627398/4d02eed3-f8a5-4ad3-a4e6-0e194353f60a)

### New Features 

added banner components
added andale mono font
added banner component stories

Fixes #10 
Fixes #9

2023-09-23 16:34 UTC, Markkos89 requested changes
Great work here @peteruche21 !! Amazing :rocket: 

Thanks a lot again, let me know if any question regarding the comments! Feel free!

2023-09-23 16:34 UTC, Markkos89 commented on packages/ui/src/components/Banners/PartnerBanner.tsx
> +          </Button>
Same thought about wrapping the button with the nextlink (viceversa)

2023-09-23 22:45 UTC, peteruche21 commented on packages/ui/src/components/Banners/LearnWeb3Banner.tsx
> +          </Button>
LOL, I'm not sure either. i basically used the example [here](https://ui.shadcn.com/docs/components/button#link) please check and let me know.

2023-09-23 22:53 UTC, peteruche21 commented on packages/ui/src/components/Banners/LearnWeb3Banner.stories.ts
> +/* eslint-disable @typescript-eslint/no-unsafe-assignment */
I'm not sure where it came from. i am just seeing it now, it appears to be on other stories too. maybe auto generated or sort.

2023-09-23 23:02 UTC, peteruche21 commented on packages/ui/src/components/Banners/LearnWeb3Banner.tsx
> +          </Button>
okay, I tested it, and it is correct the way it was implemented, doing it the other way around (i.e. wrapping the button component with the NextLink component) will cause it not to render.

2023-09-23 23:16 UTC, peteruche21 commented on packages/ui/src/components/Banners/LearnWeb3Banner.stories.ts
> +/* eslint-disable @typescript-eslint/no-unsafe-assignment */
okay, found the source.

![image](https://github.com/Developer-DAO/academy-turbo/assets/53627398/efbf44f8-0afe-46cd-bc93-32fab76d3234)

but from the type `Meta`:

```ts
type Meta<TCmpOrArgs = Args> = TCmpOrArgs extends ComponentType<any> ? ComponentAnnotations<ReactRenderer, ComponentProps<TCmpOrArgs>> : ComponentAnnotations<ReactRenderer, TCmpOrArgs>;
```

it seems `title` is indeed a member of `ComponentAnnotations`

maybe need to adjust the `eslint rules` globally or ignore on specific files.

2023-10-04 06:20 UTC, Markkos89 approved these changes

2023-10-04 07:54 UTC, merged